### ISSUE TITLE
Posthook validation

### ISSUE THREAD

**Issue by stephanmg** [UG4/ug4-packages#2]
As this package seems crucial, maybe a post hook task to validate the `package.json` markup could be reasonable, right? Anyway one would need a small script I think to validate. I found the following tools which might be useful to validate a _custom_ JSON format, e.g. ug4-packages: https://github.com/FasterXML/jackson

**Comment by sreiter** [comment]
I think a first step would be to validate your changes by yourself. Once you changed the package.json file locally, please execute 'ughub list' to check whether the syntax of the source file is valid before pushing your changes to the repository.
Please note that our internal jenkins setup tests the sources automatically by installing all packages during each test.

**Comment by stephanmg** [comment]
Ok, but this test should also be available on Github at some point.
Maybe reference your Travis CI status from _ugcore_ project here, just an idea. 
Best regards.
